// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: clickhouse.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Retailer entity with optional fields
type Retailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                // UUID v4 (optional if not in SELECT)
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`                            // String (optional if not in SELECT)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"` // DateTime (optional if not in SELECT)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Retailer) Reset() {
	*x = Retailer{}
	mi := &file_clickhouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Retailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retailer) ProtoMessage() {}

func (x *Retailer) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retailer.ProtoReflect.Descriptor instead.
func (*Retailer) Descriptor() ([]byte, []int) {
	return file_clickhouse_proto_rawDescGZIP(), []int{0}
}

func (x *Retailer) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Retailer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Retailer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Get multiple retailers with SQL query
type GetRetailersRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SqlQuery   string                 `protobuf:"bytes,1,opt,name=sql_query,json=sqlQuery,proto3" json:"sql_query,omitempty"`                                                               // SQL query to execute
	Parameters map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Named parameters for the query
	// Optional pagination (applied after the query)
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRetailersRequest) Reset() {
	*x = GetRetailersRequest{}
	mi := &file_clickhouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetailersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailersRequest) ProtoMessage() {}

func (x *GetRetailersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailersRequest.ProtoReflect.Descriptor instead.
func (*GetRetailersRequest) Descriptor() ([]byte, []int) {
	return file_clickhouse_proto_rawDescGZIP(), []int{1}
}

func (x *GetRetailersRequest) GetSqlQuery() string {
	if x != nil {
		return x.SqlQuery
	}
	return ""
}

func (x *GetRetailersRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GetRetailersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRetailersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRetailersResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Retailers       []*Retailer            `protobuf:"bytes,1,rep,name=retailers,proto3" json:"retailers,omitempty"`                                       // Toujours présent, même si vide []
	Count           int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                                              // Toujours présent, même si 0
	ExecutionTimeMs int64                  `protobuf:"varint,3,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"` // Toujours présent
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                               // Seulement si erreur
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRetailersResponse) Reset() {
	*x = GetRetailersResponse{}
	mi := &file_clickhouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetailersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailersResponse) ProtoMessage() {}

func (x *GetRetailersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailersResponse.ProtoReflect.Descriptor instead.
func (*GetRetailersResponse) Descriptor() ([]byte, []int) {
	return file_clickhouse_proto_rawDescGZIP(), []int{2}
}

func (x *GetRetailersResponse) GetRetailers() []*Retailer {
	if x != nil {
		return x.Retailers
	}
	return nil
}

func (x *GetRetailersResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetRetailersResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *GetRetailersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Streaming response for large datasets
type RetailerStreamResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Retailer        *Retailer              `protobuf:"bytes,1,opt,name=retailer,proto3" json:"retailer,omitempty"`
	IsLast          bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,3,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"` // Temps d'exécution total du stream (seulement dans le dernier message)
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetailerStreamResponse) Reset() {
	*x = RetailerStreamResponse{}
	mi := &file_clickhouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetailerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetailerStreamResponse) ProtoMessage() {}

func (x *RetailerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetailerStreamResponse.ProtoReflect.Descriptor instead.
func (*RetailerStreamResponse) Descriptor() ([]byte, []int) {
	return file_clickhouse_proto_rawDescGZIP(), []int{3}
}

func (x *RetailerStreamResponse) GetRetailer() *Retailer {
	if x != nil {
		return x.Retailer
	}
	return nil
}

func (x *RetailerStreamResponse) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *RetailerStreamResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *RetailerStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_clickhouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_clickhouse_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_clickhouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_clickhouse_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_clickhouse_proto protoreflect.FileDescriptor

const file_clickhouse_proto_rawDesc = "" +
	"\n" +
	"\x10clickhouse.proto\x12\n" +
	"clickhouse\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\bRetailer\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tcreatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\r\n" +
	"\v_created_at\"\xf0\x01\n" +
	"\x13GetRetailersRequest\x12\x1b\n" +
	"\tsql_query\x18\x01 \x01(\tR\bsqlQuery\x12O\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2/.clickhouse.GetRetailersRequest.ParametersEntryR\n" +
	"parameters\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\x14GetRetailersResponse\x122\n" +
	"\tretailers\x18\x01 \x03(\v2\x14.clickhouse.RetailerR\tretailers\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12*\n" +
	"\x11execution_time_ms\x18\x03 \x01(\x03R\x0fexecutionTimeMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xa5\x01\n" +
	"\x16RetailerStreamResponse\x120\n" +
	"\bretailer\x18\x01 \x01(\v2\x14.clickhouse.RetailerR\bretailer\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\x12*\n" +
	"\x11execution_time_ms\x18\x03 \x01(\x03R\x0fexecutionTimeMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"\x86\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x93\x02\n" +
	"\x11ClickHouseService\x12N\n" +
	"\vHealthCheck\x12\x1e.clickhouse.HealthCheckRequest\x1a\x1f.clickhouse.HealthCheckResponse\x12Q\n" +
	"\fGetRetailers\x12\x1f.clickhouse.GetRetailersRequest\x1a .clickhouse.GetRetailersResponse\x12[\n" +
	"\x12GetRetailersStream\x12\x1f.clickhouse.GetRetailersRequest\x1a\".clickhouse.RetailerStreamResponse0\x01B&Z$api-retailers-nest/packages/proto/gob\x06proto3"

var (
	file_clickhouse_proto_rawDescOnce sync.Once
	file_clickhouse_proto_rawDescData []byte
)

func file_clickhouse_proto_rawDescGZIP() []byte {
	file_clickhouse_proto_rawDescOnce.Do(func() {
		file_clickhouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clickhouse_proto_rawDesc), len(file_clickhouse_proto_rawDesc)))
	})
	return file_clickhouse_proto_rawDescData
}

var file_clickhouse_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_clickhouse_proto_goTypes = []any{
	(*Retailer)(nil),               // 0: clickhouse.Retailer
	(*GetRetailersRequest)(nil),    // 1: clickhouse.GetRetailersRequest
	(*GetRetailersResponse)(nil),   // 2: clickhouse.GetRetailersResponse
	(*RetailerStreamResponse)(nil), // 3: clickhouse.RetailerStreamResponse
	(*HealthCheckRequest)(nil),     // 4: clickhouse.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 5: clickhouse.HealthCheckResponse
	nil,                            // 6: clickhouse.GetRetailersRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_clickhouse_proto_depIdxs = []int32{
	7, // 0: clickhouse.Retailer.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: clickhouse.GetRetailersRequest.parameters:type_name -> clickhouse.GetRetailersRequest.ParametersEntry
	0, // 2: clickhouse.GetRetailersResponse.retailers:type_name -> clickhouse.Retailer
	0, // 3: clickhouse.RetailerStreamResponse.retailer:type_name -> clickhouse.Retailer
	4, // 4: clickhouse.ClickHouseService.HealthCheck:input_type -> clickhouse.HealthCheckRequest
	1, // 5: clickhouse.ClickHouseService.GetRetailers:input_type -> clickhouse.GetRetailersRequest
	1, // 6: clickhouse.ClickHouseService.GetRetailersStream:input_type -> clickhouse.GetRetailersRequest
	5, // 7: clickhouse.ClickHouseService.HealthCheck:output_type -> clickhouse.HealthCheckResponse
	2, // 8: clickhouse.ClickHouseService.GetRetailers:output_type -> clickhouse.GetRetailersResponse
	3, // 9: clickhouse.ClickHouseService.GetRetailersStream:output_type -> clickhouse.RetailerStreamResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_clickhouse_proto_init() }
func file_clickhouse_proto_init() {
	if File_clickhouse_proto != nil {
		return
	}
	file_clickhouse_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clickhouse_proto_rawDesc), len(file_clickhouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clickhouse_proto_goTypes,
		DependencyIndexes: file_clickhouse_proto_depIdxs,
		MessageInfos:      file_clickhouse_proto_msgTypes,
	}.Build()
	File_clickhouse_proto = out.File
	file_clickhouse_proto_goTypes = nil
	file_clickhouse_proto_depIdxs = nil
}
